### PR TITLE
Added solopool.org pool

### PR DESCRIPTION
**Pull request by diomark**

### CODE REVIEW

**Comment by MaudSimon** [comment]
@Sakrecoer Can you have a look and merge or close accordingly ?

**Comment by Sakrecoer** [comment]
Thanks @diomark ! Unclear why this didn't reach me until now...

The PR looks good to me, but i suppose we would need to add the disclaimer here as well... :thought_balloon:  I had completely forgotten that there was a list of pools here too :sweat_smile: 

I will also add this pool to the list on wiki. Perhaps we should remove the list from here as to not have 2 places where we have to update this type of information. @MaudSimon

**Comment by MaudSimon** [comment]
@Sakrecoer I agree with not duplicating the list.  However, maybe the right place for the list is in this repo (vs the FAQ), this way it's even more clear that the pools are not run by Alephium. Not sure. Wdyt?

**Comment by Sakrecoer** [comment]
@MaudSimon: I think it's better in the wiki (not the FAQ, it's under the mining section). I think it's the kind of information one would search for in the wiki, feels more natural than a specific repo on github. However, i did put the link to the dedicated wiki section in this repo. Since the wiki is also editable by the community via the same process of PR on github, it think it makes more sense this way. :)

**Pull request closed without merging**
